name: Build this Docker image
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: master
  # schedule:
  #   - cron: '11 23 * * 0'

jobs:

  test:
    name: check Ansible availability
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Test building image.
        run: docker build -t worksuite .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro worksuite

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm ansible --version

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout DevOpsAnsibleDE NextCloud Repo
        uses: actions/checkout@v3
        with:
          ref: master
          path: ws

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: devopsansiblede/worksuite:latest
          no-cache: true
          context: ./ws/
          file: ./ws/Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Last Built Date
        run: sed -i -E "s/^[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}$/$( date +"%Y-%m-%d %T" )/" ./nextcloud/README.md

      - name: Commit last built
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Last built
          commit_user_name: GitHub Actions
          commit_user_email: dev@macwinnie.me
          repository: ./ws/
